import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';

import 'core/theme/app_theme.dart';
import 'core/router/app_router.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

Future<void> main() async {
  // Ensures Flutter engine is ready before calling any platform channels
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase before the app renders
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    // ProviderScope is the root of Riverpod — all providers live inside it.
    // Wrap ONLY the root widget, not MaterialApp.
    const ProviderScope(
      child: NimaApp(),
    ),
  );
}

/// Root application widget.
///
/// [ConsumerWidget] (vs StatelessWidget) lets us watch Riverpod providers.
/// Here we use it to obtain the [GoRouter] instance that is auth-aware.
class NimaApp extends ConsumerWidget {
  const NimaApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Watch the router — it rebuilds when auth state changes,
    // which triggers GoRouter's redirect logic automatically.
    final router = ref.watch(appRouterProvider);

    return MaterialApp.router(
      title: 'NIMA',
      debugShowCheckedModeBanner: false,

      // ── Theme ─────────────────────────────────────────────────────────────
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      themeAnimationDuration: Duration.zero,

      // ── Router ────────────────────────────────────────────────────────────
      routerConfig: router,
    );
  }
}
